/*
 * ESPectre - MLDetector Unit Tests
 *
 * Tests the MLDetector class implementing BaseDetector interface.
 * Validates MLP inference accuracy against reference model outputs.
 * Test data is loaded from ml_test_data.npz (auto-generated by training script).
 *
 * Author: Francesco Pace <francesco.pace@gmail.com>
 * License: GPLv3
 */

#include <unity.h>
#include <cstdint>
#include <cstring>
#include <cmath>
#include <algorithm>
#include <vector>
#include "ml_detector.h"
#include "ml_features.h"
#include "ml_weights.h"
#include "espectre.h"
#include "esphome/core/log.h"
#include "cnpy.cpp"

using namespace esphome::espectre;
static_assert(ML_MODEL_INPUT_SIZE == ML_NUM_FEATURES,
              "Exported model input size must match extracted ML feature count");

static const char *TEST_TAG = "test_ml_detector";

// ============================================================================
// TEST DATA (loaded from ml_test_data.npz at runtime)
// ============================================================================

#define ML_TEST_DATA_PATH "../micro-espectre/models/ml_test_data.npz"

// Sample indices to test (spread across the dataset)
static const int SAMPLE_INDICES[] = {0, 100, 500, 1000, 2000, 2500};
static const int NUM_SAMPLE_INDICES = sizeof(SAMPLE_INDICES) / sizeof(SAMPLE_INDICES[0]);

// Loaded test data
static std::vector<std::vector<float>> test_features;
static std::vector<float> test_expected;
static std::vector<int> test_labels;
static int num_test_samples = 0;
static bool data_loaded = false;

static void load_test_data() {
    if (data_loaded) return;
    
    cnpy::npz_t npz = cnpy::npz_load(ML_TEST_DATA_PATH);
    
    // Load features: shape [N, num_features]
    cnpy::NpyArray& feat_arr = npz["features"];
    int total_samples = static_cast<int>(feat_arr.shape[0]);
    int num_features = static_cast<int>(feat_arr.shape[1]);
    const float* feat_data = feat_arr.data<float>();
    TEST_ASSERT_EQUAL_INT_MESSAGE(ML_MODEL_INPUT_SIZE, num_features,
                                  "ml_test_data feature count must match exported model input size");
    
    // Load expected outputs: shape [N]
    cnpy::NpyArray& exp_arr = npz["expected_outputs"];
    const float* exp_data = exp_arr.data<float>();
    
    // Load labels: shape [N]
    cnpy::NpyArray& label_arr = npz["labels"];
    const int32_t* label_data = label_arr.data<int32_t>();
    
    // Extract samples at specified indices
    for (int i = 0; i < NUM_SAMPLE_INDICES; i++) {
        int idx = SAMPLE_INDICES[i];
        if (idx >= total_samples) break;
        
        std::vector<float> features(num_features);
        for (int j = 0; j < num_features; j++) {
            features[j] = feat_data[idx * num_features + j];
        }
        test_features.push_back(features);
        test_expected.push_back(exp_data[idx]);
        test_labels.push_back(static_cast<int>(label_data[idx]));
        num_test_samples++;
    }
    
    ESP_LOGI(TEST_TAG, "Loaded %d test samples from %s (total: %d)", 
             num_test_samples, ML_TEST_DATA_PATH, total_samples);
    data_loaded = true;
}

void setUp(void) { load_test_data(); }
void tearDown(void) {}

// ============================================================================
// INITIALIZATION TESTS
// ============================================================================

void test_ml_detector_default_constructor(void) {
    MLDetector detector;
    
    TEST_ASSERT_EQUAL(DETECTOR_DEFAULT_WINDOW_SIZE, detector.get_window_size());
    TEST_ASSERT_EQUAL_FLOAT(ML_DEFAULT_THRESHOLD, detector.get_threshold());
    TEST_ASSERT_EQUAL(MotionState::IDLE, detector.get_state());
    TEST_ASSERT_EQUAL(0, detector.get_total_packets());
}

void test_ml_detector_custom_constructor(void) {
    MLDetector detector(100, 7.0f);
    
    TEST_ASSERT_EQUAL(100, detector.get_window_size());
    TEST_ASSERT_EQUAL_FLOAT(7.0f, detector.get_threshold());
}

void test_ml_detector_get_name(void) {
    MLDetector detector;
    
    TEST_ASSERT_EQUAL_STRING("ML", detector.get_name());
}

// ============================================================================
// THRESHOLD TESTS
// ============================================================================

void test_ml_detector_set_threshold_valid(void) {
    MLDetector detector;
    
    TEST_ASSERT_TRUE(detector.set_threshold(7.0f));
    TEST_ASSERT_EQUAL_FLOAT(7.0f, detector.get_threshold());
}

void test_ml_detector_set_threshold_min(void) {
    MLDetector detector;
    
    TEST_ASSERT_TRUE(detector.set_threshold(ML_MIN_THRESHOLD));
    TEST_ASSERT_EQUAL_FLOAT(ML_MIN_THRESHOLD, detector.get_threshold());
}

void test_ml_detector_set_threshold_max(void) {
    MLDetector detector;
    
    TEST_ASSERT_TRUE(detector.set_threshold(ML_MAX_THRESHOLD));
    TEST_ASSERT_EQUAL_FLOAT(ML_MAX_THRESHOLD, detector.get_threshold());
}

void test_ml_detector_set_threshold_below_min(void) {
    MLDetector detector;
    float original = detector.get_threshold();
    
    TEST_ASSERT_FALSE(detector.set_threshold(-0.1f));
    TEST_ASSERT_EQUAL_FLOAT(original, detector.get_threshold());
}

void test_ml_detector_set_threshold_above_max(void) {
    MLDetector detector;
    float original = detector.get_threshold();
    
    TEST_ASSERT_FALSE(detector.set_threshold(10.1f));
    TEST_ASSERT_EQUAL_FLOAT(original, detector.get_threshold());
}

// ============================================================================
// MLP INFERENCE TESTS
// ============================================================================

// Helper function to run MLP inference (same as MLDetector::predict)
static float run_inference(const float* features) {
    constexpr size_t kBufferSize =
        (ML_MAX_LAYER_WIDTH > ML_MODEL_INPUT_SIZE) ? ML_MAX_LAYER_WIDTH : ML_MODEL_INPUT_SIZE;
    float buffer_a[kBufferSize] = {0.0f};
    float buffer_b[kBufferSize] = {0.0f};

    // Normalize raw features using StandardScaler params
    for (int i = 0; i < ML_MODEL_INPUT_SIZE; i++) {
        buffer_a[i] = (features[i] - ML_FEATURE_MEAN[i]) / ML_FEATURE_SCALE[i];
    }

    float* current = buffer_a;
    float* next = buffer_b;
    float out = 0.0f;

    for (int layer = 0; layer < ML_MODEL_NUM_LAYERS; layer++) {
        const int in_size = ML_MODEL_LAYER_INPUT_SIZES[layer];
        const int out_size = ML_MODEL_LAYER_OUTPUT_SIZES[layer];
        const float* weights = ML_MODEL_WEIGHTS[layer];
        const float* biases = ML_MODEL_BIASES[layer];
        const bool is_output_layer = (layer == ML_MODEL_NUM_LAYERS - 1);

        for (int j = 0; j < out_size; j++) {
            float val = biases[j];
            for (int i = 0; i < in_size; i++) {
                val += current[i] * weights[i * out_size + j];
            }

            if (is_output_layer) {
                out = val;
            } else {
                next[j] = std::max(0.0f, val);
            }
        }

        if (!is_output_layer) {
            std::swap(current, next);
        }
    }

    out /= ML_TEMPERATURE;

    // Sigmoid with overflow protection and scaling to 0-10
    if (out < -20.0f) return 0.0f;
    if (out > 20.0f) return ML_METRIC_SCALE;
    return (1.0f / (1.0f + std::exp(-out))) * ML_METRIC_SCALE;
}

void test_ml_inference_matches_reference(void) {
    const float TOLERANCE = 1e-4f;  // Allow small numerical error
    TEST_ASSERT_TRUE_MESSAGE(num_test_samples > 0, "No test data loaded");
    
    for (int i = 0; i < num_test_samples; i++) {
        float result = run_inference(test_features[i].data());
        float expected = test_expected[i] * ML_METRIC_SCALE;
        float error = std::abs(result - expected);
        
        ESP_LOGD(TEST_TAG, "Sample %d (idx=%d): expected=%.6f, got=%.6f, error=%.2e",
                 i, SAMPLE_INDICES[i], expected, result, error);
        
        TEST_ASSERT_FLOAT_WITHIN(TOLERANCE, expected, result);
    }
}

void test_ml_inference_output_range(void) {
    TEST_ASSERT_TRUE_MESSAGE(num_test_samples > 0, "No test data loaded");
    
    for (int i = 0; i < num_test_samples; i++) {
        float result = run_inference(test_features[i].data());
        
        TEST_ASSERT_TRUE(result >= 0.0f);
        TEST_ASSERT_TRUE(result <= ML_METRIC_SCALE);
    }
}

void test_ml_inference_classification(void) {
    // Test that motion/idle classification is correct
    const float THRESHOLD = ML_DEFAULT_THRESHOLD;
    TEST_ASSERT_TRUE_MESSAGE(num_test_samples > 0, "No test data loaded");
    
    for (int i = 0; i < num_test_samples; i++) {
        float result = run_inference(test_features[i].data());
        float expected = test_expected[i] * ML_METRIC_SCALE;
        
        bool result_motion = (result > THRESHOLD);
        bool expected_motion = (expected > THRESHOLD);
        
        TEST_ASSERT_EQUAL(expected_motion, result_motion);
    }
}

// ============================================================================
// FEATURE EXTRACTION TESTS
// ============================================================================

void test_feature_extraction_basic(void) {
    float turb_buffer[50];
    float amplitudes[12] = {10.0f, 12.0f, 11.0f, 13.0f, 9.0f, 14.0f,
                            10.5f, 11.5f, 12.5f, 10.0f, 11.0f, 13.0f};
    float features[ML_NUM_FEATURES];
    
    // Fill buffer with synthetic data
    for (int i = 0; i < 50; i++) {
        turb_buffer[i] = 10.0f + (i % 5) * 0.5f;
    }
    
    extract_ml_features(turb_buffer, 50, amplitudes, 12, features);
    
    // Verify features are reasonable
    // Order: mean, std, max, min, iqr, skewness, autocorr, mad, waveform_length
    TEST_ASSERT_TRUE(features[0] > 0);   // turb_mean > 0
    TEST_ASSERT_TRUE(features[1] >= 0);  // turb_std >= 0
    TEST_ASSERT_TRUE(features[2] >= features[3]); // turb_max >= turb_min
    TEST_ASSERT_TRUE(features[4] >= 0);  // turb_iqr >= 0
    // features[5] = skewness (can be any value)
    TEST_ASSERT_TRUE(features[6] >= -1.0f && features[6] <= 1.0f);  // autocorr in [-1, 1]
    TEST_ASSERT_TRUE(features[7] >= 0);  // turb_mad >= 0
    TEST_ASSERT_TRUE(features[8] >= 0);  // waveform_length >= 0
}

void test_feature_extraction_empty_buffer(void) {
    float turb_buffer[50] = {0};
    float features[ML_NUM_FEATURES];
    
    extract_ml_features(turb_buffer, 0, nullptr, 0, features);
    
    // All features should be 0 for empty buffer
    for (int i = 0; i < ML_NUM_FEATURES; i++) {
        TEST_ASSERT_EQUAL_FLOAT(0.0f, features[i]);
    }
}

// ============================================================================
// ML SUBCARRIERS TESTS
// ============================================================================

void test_ml_subcarriers_count(void) {
    TEST_ASSERT_EQUAL(12, sizeof(DEFAULT_SUBCARRIERS) / sizeof(DEFAULT_SUBCARRIERS[0]));
}

void test_ml_subcarriers_range(void) {
    for (int i = 0; i < 12; i++) {
        TEST_ASSERT_TRUE(DEFAULT_SUBCARRIERS[i] >= 0);
        TEST_ASSERT_TRUE(DEFAULT_SUBCARRIERS[i] < 64);  // HT20 has 64 subcarriers
    }
}

void test_ml_subcarriers_sorted(void) {
    for (int i = 1; i < 12; i++) {
        TEST_ASSERT_TRUE(DEFAULT_SUBCARRIERS[i] > DEFAULT_SUBCARRIERS[i-1]);
    }
}

// ============================================================================
// PERFORMANCE TESTS
// ============================================================================

void test_ml_inference_performance(void) {
    const int NUM_ITERATIONS = 1000;
    
    TEST_ASSERT_TRUE_MESSAGE(num_test_samples > 0, "No test data loaded");
    
    // Warm up
    for (int i = 0; i < 10; i++) {
        run_inference(test_features[0].data());
    }
    
    // Benchmark (note: on native platform, not on actual ESP32)
    uint32_t start = 0;  // Would use micros() on ESP32
    
    for (int i = 0; i < NUM_ITERATIONS; i++) {
        run_inference(test_features[i % num_test_samples].data());
    }
    
    uint32_t elapsed = 0;  // Would calculate elapsed time
    
    // Just verify it completes without error
    ESP_LOGI(TEST_TAG, "Completed %d inference iterations", NUM_ITERATIONS);
    TEST_PASS();
}

// ============================================================================
// MAIN
// ============================================================================

int main(int argc, char **argv) {
    UNITY_BEGIN();
    
    // Initialization tests
    RUN_TEST(test_ml_detector_default_constructor);
    RUN_TEST(test_ml_detector_custom_constructor);
    RUN_TEST(test_ml_detector_get_name);
    
    // Threshold tests
    RUN_TEST(test_ml_detector_set_threshold_valid);
    RUN_TEST(test_ml_detector_set_threshold_min);
    RUN_TEST(test_ml_detector_set_threshold_max);
    RUN_TEST(test_ml_detector_set_threshold_below_min);
    RUN_TEST(test_ml_detector_set_threshold_above_max);
    
    // MLP inference tests
    RUN_TEST(test_ml_inference_matches_reference);
    RUN_TEST(test_ml_inference_output_range);
    RUN_TEST(test_ml_inference_classification);
    
    // Feature extraction tests
    RUN_TEST(test_feature_extraction_basic);
    RUN_TEST(test_feature_extraction_empty_buffer);
    
    // Subcarriers tests
    RUN_TEST(test_ml_subcarriers_count);
    RUN_TEST(test_ml_subcarriers_range);
    RUN_TEST(test_ml_subcarriers_sorted);
    
    // Performance tests
    RUN_TEST(test_ml_inference_performance);
    
    return UNITY_END();
}
