"""
Micro-ESPectre - ML Motion Detector

Neural network-based motion detector implementing the IDetector interface.
Uses pre-trained weights from ml_weights.py (auto-generated by training script).

Usage:
    from ml_detector import MLDetector
    
    detector = MLDetector()
    detector.process_packet(csi_data, subcarriers)
    metrics = detector.update_state()

Author: Francesco Pace <francesco.pace@gmail.com>
License: GPLv3
"""
import math

try:
    from src.detector_interface import IDetector, MotionState
    from src.segmentation import SegmentationContext
    from src.features import extract_features_by_name
    from src.config import DEFAULT_SUBCARRIERS
except ImportError:
    from detector_interface import IDetector, MotionState
    from segmentation import SegmentationContext
    from features import extract_features_by_name
    from config import DEFAULT_SUBCARRIERS

try:
    from src.ml_weights import (
        FEATURE_MEAN, FEATURE_SCALE,
        MODEL_LAYER_SIZES, WEIGHTS, BIASES, FEATURE_NAMES,
    )
except ImportError:
    from ml_weights import (
        FEATURE_MEAN, FEATURE_SCALE,
        MODEL_LAYER_SIZES, WEIGHTS, BIASES, FEATURE_NAMES,
    )

# Re-export for convenience
__all__ = ['MLDetector', 'predict', 'is_motion', 'DEFAULT_SUBCARRIERS', 'FEATURE_NAMES']

# ML-specific constants (unified with MVS for consistent UI)
ML_DEFAULT_THRESHOLD = 5.0
ML_MIN_THRESHOLD = 0.0
ML_MAX_THRESHOLD = 10.0
ML_METRIC_SCALE = 10.0
ML_TEMPERATURE = 5.0

# Transpose weight matrices at load time: [input][output] → [output][input].
# This makes the inner multiply-add loop access weights[j] once per output
# neuron instead of weights[i][j] (2 lookups) per multiply-add.
_WEIGHTS_T = []
for _lw in WEIGHTS:
    _n_in = len(_lw)
    _n_out = len(_lw[0])
    _WEIGHTS_T.append([[_lw[i][j] for i in range(_n_in)] for j in range(_n_out)])
del _lw, _n_in, _n_out

# ============================================================================
# Neural Network Inference Functions
# ============================================================================

def relu(x):
    """ReLU activation function."""
    return x if x > 0 else 0.0


def sigmoid(x):
    """Sigmoid activation function with overflow protection."""
    if x < -20:
        return 0.0
    if x > 20:
        return 1.0
    return 1.0 / (1.0 + math.exp(-x))


def normalize_features(features):
    """Normalize features using pre-computed mean and scale."""
    if len(features) != len(FEATURE_MEAN):
        raise ValueError(
            f"Expected {len(FEATURE_MEAN)} features, got {len(features)}"
        )
    normalized = []
    for i in range(len(features)):
        normalized.append((features[i] - FEATURE_MEAN[i]) / FEATURE_SCALE[i])
    return normalized


def predict(features):
    """
    Predict motion probability from the exported feature vector.
    
    Args:
        features: Ordered feature vector expected by the exported model
    
    Returns:
        float: Scaled motion metric (0.0 to 10.0)
    """
    n_feat = len(features)
    activations = [0.0] * n_feat
    for i in range(n_feat):
        activations[i] = (features[i] - FEATURE_MEAN[i]) / FEATURE_SCALE[i]

    n_layers = len(_WEIGHTS_T)
    for layer_idx in range(n_layers):
        weights_t = _WEIGHTS_T[layer_idx]
        biases = BIASES[layer_idx]
        n_out = len(biases)
        next_activations = [0.0] * n_out
        is_last = layer_idx == n_layers - 1
        for j in range(n_out):
            val = biases[j]
            w_row = weights_t[j]
            for i in range(len(activations)):
                val += activations[i] * w_row[i]
            next_activations[j] = val if is_last else (val if val > 0 else 0.0)
        activations = next_activations

    return sigmoid(activations[0] / ML_TEMPERATURE) * ML_METRIC_SCALE


def is_motion(features, threshold=ML_DEFAULT_THRESHOLD):
    """
    Detect motion from features.
    
    Args:
        features: Ordered feature vector expected by the exported model
        threshold: Detection threshold (default: 5.0)
    
    Returns:
        bool: True if motion detected
    """
    return predict(features) > threshold


# ============================================================================
# MLDetector Class
# ============================================================================


class MLDetector(IDetector):
    """
    Neural Network-based motion detector.
    
    Uses a pre-trained MLP exported by the training pipeline to classify
    motion based on turbulence features extracted from CSI data.
    
    Algorithm:
    1. Calculate spatial turbulence (std of subcarrier amplitudes)
    2. Store in circular buffer (window_size packets)
    3. Extract the configured ML feature vector from buffer
    4. Run neural network inference
    5. Compare probability to threshold for state decision
    """
    
    def __init__(self, window_size=100, threshold=ML_DEFAULT_THRESHOLD,
                 enable_lowpass=False, lowpass_cutoff=11.0,
                 enable_hampel=True, hampel_window=7, hampel_threshold=5.0,
                 **kwargs):
        """
        Initialize ML detector.
        
        Args:
            window_size: Feature extraction window size (default: 100, matches C++ DETECTOR_DEFAULT_WINDOW_SIZE)
            threshold: Motion detection threshold (default: 5.0, range 0.0-10.0)
            enable_lowpass: Enable low-pass filter (default: False)
            lowpass_cutoff: Low-pass cutoff frequency Hz (default: 11.0)
            enable_hampel: Enable Hampel filter (default: True, model trained with Hampel)
            hampel_window: Hampel window size (default: 7)
            hampel_threshold: Hampel threshold in MAD (default: 5.0)
        """
        # Use SegmentationContext for turbulence calculation and filtering
        self._context = SegmentationContext(
            window_size=window_size,
            threshold=1.0,  # Not used, we use probability threshold
            enable_lowpass=enable_lowpass,
            lowpass_cutoff=lowpass_cutoff,
            enable_hampel=enable_hampel,
            hampel_window=hampel_window,
            hampel_threshold=hampel_threshold
        )
        # ML model is trained on raw std only — CV normalization must stay off
        self._context.use_cv_normalization = False
        self._threshold = threshold
        self._packet_count = 0
        self._motion_count = 0
        self._state = MotionState.IDLE
        self._current_probability = 0.0
        
        # For tracking (optional)
        self.probability_history = []
        self.state_history = []
        self.track_data = False
    
    def process_packet(self, csi_data, selected_subcarriers=None):
        """
        Process a CSI packet.
        
        Args:
            csi_data: Raw CSI data (int8 I/Q pairs)
            selected_subcarriers: Subcarrier indices to use
        """
        self._packet_count += 1
        
        # ML features use only the turbulence window; skip per-packet amplitude lists.
        turbulence = self._context.calculate_spatial_turbulence(
            csi_data, selected_subcarriers
        )

        # Add to buffer
        self._context.add_turbulence(turbulence)
    
    def update_state(self):
        """
        Run inference and update state.
        
        Returns:
            dict: Current metrics including state and probability
        """
        if not self.is_ready():
            return {
                'state': self._state,
                'probability': 0.0,
                'threshold': self._threshold
            }
        
        # Extract features from turbulence buffer
        features = self._extract_features()
        
        # Run neural network
        self._current_probability = predict(features)
        
        # Update state
        if self._current_probability > self._threshold:
            self._state = MotionState.MOTION
        else:
            self._state = MotionState.IDLE
        
        if self.track_data:
            self.probability_history.append(self._current_probability)
            state_str = 'MOTION' if self._state == MotionState.MOTION else 'IDLE'
            self.state_history.append(state_str)
            if self._state == MotionState.MOTION:
                self._motion_count += 1
        
        return {
            'state': self._state,
            'probability': self._current_probability,
            'threshold': self._threshold
        }
    
    def _extract_features(self):
        """
        Extract the configured feature vector from turbulence buffer.
        
        IMPORTANT: The turbulence_buffer is a circular buffer. After wrap-around,
        a simple slice [:buffer_count] would NOT be in chronological order.
        Features like slope, delta, zcr, and autocorr depend on temporal order.
        
        We reconstruct the chronological order: [oldest ... newest]
        """
        ctx = self._context
        
        # Build chronological list from circular buffer
        if ctx.buffer_count < ctx.window_size:
            # Buffer not full yet: data is in order from index 0
            turb_list = ctx.turbulence_buffer[:ctx.buffer_count]
        else:
            # Buffer is full and has wrapped: reconstruct order
            # buffer_index points to the NEXT write position (oldest value)
            idx = ctx.buffer_index
            turb_list = ctx.turbulence_buffer[idx:] + ctx.turbulence_buffer[:idx]
        
        return extract_features_by_name(
            turb_list, len(turb_list),
            feature_names=FEATURE_NAMES
        )
    
    def get_state(self):
        """Get current motion state."""
        return self._state
    
    def get_motion_metric(self):
        """Get current motion probability."""
        return self._current_probability
    
    def get_threshold(self):
        """Get current probability threshold."""
        return self._threshold
    
    def set_threshold(self, threshold):
        """Set threshold (range 0.0-10.0, unified with MVS)."""
        if ML_MIN_THRESHOLD <= threshold <= ML_MAX_THRESHOLD:
            self._threshold = threshold
            return True
        return False

    def set_cv_normalization(self, enabled):
        """
        Ignore CV normalization requests.

        The exported ML model is trained on raw standard deviation, so the
        runtime must keep CV normalization disabled to stay aligned with the
        C++ implementation and the training pipeline.
        """
        del enabled
        self._context.use_cv_normalization = False
    
    def is_ready(self):
        """Check if buffer is full."""
        return self._context.buffer_count >= self._context.window_size
    
    def reset(self):
        """Reset detector state."""
        self._context.reset(full=True)
        self._state = MotionState.IDLE
        self._current_probability = 0.0
        self._motion_count = 0
        self.probability_history = []
        self.state_history = []
    
    def get_name(self):
        """Get detector name."""
        return "ML"
    
    @property
    def total_packets(self):
        """Total packets processed."""
        return self._packet_count
    
    def get_motion_count(self):
        """Get number of motion detections (for tracking)."""
        return self._motion_count
